project_name: {{ pillar['project_client']|title }} {{ pillar['project_name']|title|replace('_', ' ') }}
project_root: {{ pillar['root_dir'] }}/{{ pillar['project_name'] }}
pre:
  - git up
  - vim +BundleClean +BundleInstall +qall
tabs:
  - Vim:
        layout: 1dfc,238x67,0,0{150x67,0,0,87x67,151,0[87x33,151,0,87x33,151,34]}
        panes:
          - workon {{ pillar['project_name'] }} && vim
          - workon {{ pillar['project_name'] }} && make run_django
          - workon {{ pillar['project_name'] }}
  - Shell: workon {{ pillar['project_name'] }}
  - Tests: workon {{ pillar['project_name'] }} && django-admin.py test
